---
- name: Install dev dependencies
  hosts: localhost
  connection: local

  tasks:
    - name: Install dependencies (Ubuntu)
      apt:
        name: "{{ item }}"
        state: present
      with_items:
        - entr # File watcher
        - ripgrep # Fast search tool
        - just # Task runner
      when: ansible_os_family == 'Debian'
      become: yes

    - name: Install dependencies (macOS)
      homebrew:
        name: "{{ item }}"
      with_items:
        - entr # File watcher
        - ripgrep # Fast search tool
        - just # Task runner
      when: ansible_os_family == 'Darwin'
