---
# This playbook is used to test the project template by executing the
# django-admin startproject command.
- hosts: localhost
  connection: local

  vars:
    clean_up: true
    project_name: TEST_PROJECT_NAME
    django_version: "5.2.8"
    install_project_dependencies: true
    setup_project: true
    project_dir: null

  tasks:
    - name: Check if the django-admin command is available
      ansible.builtin.command:
        cmd: django-admin --version
      register: django_admin_version
      failed_when: django_admin_version.rc != 0

    - name: Check if .env file exists as this seems to fail if it isn't
      ansible.builtin.stat:
        path: "{{ playbook_dir }}/../../django_project_template/project_name/.env"
      register: env_file

    - name: Make a copy of .env.dist to .env if not already present
      ansible.builtin.copy:
        src: "{{ playbook_dir }}/../../django_project_template/project_name/.env.dist"
        dest: "{{ playbook_dir }}/../../django_project_template/project_name/.env"
      when: env_file.stat.exists == false

    - name: Use a temporary directory if project_dir is not set
      when: not project_dir | bool
      block:
        - name: Generate a temporary directory for this test
          ansible.builtin.tempfile:
            state: directory
            prefix: ansible_django_project_template
          register: temp_dir

        - name: Set the temp_dir as the project_dir
          set_fact:
            project_dir: "{{ temp_dir.path }}"

        - name: Clean up old temporary directories
          when: clean_up
          block:
            - name: Find all temp directories
              ansible.builtin.find:
                paths:
                  - "{{ (project_dir, '..') | path_join }}"
                patterns:
                  - "ansible_django_project_template*"
                file_type: directory
              register: temp_dirs

            - name: Remove temp directories
              ansible.builtin.file:
                state: absent
                path: "{{ item }}"
              with_items: "{{ temp_dirs.files | map(attribute='path') }}"

    - name: Create the project directory
      ansible.builtin.file:
        path: "{{ item }}"
        state: directory
      with_items:
        - "{{ project_dir }}"

    - name: Share the name of the temporary directory with the user
      debug:
        msg: "{{ project_dir }}"

    - name: Use the template to start a new Django project
      ansible.builtin.command:
        cmd: |
          django-admin startproject
            --template={{ playbook_dir }}/..
            --extension 'py,yaml,md,template,dist,toml,json,css,js,dev,prod'
            --name Justfile
            --exclude '.ruff_cache'
            --exclude 'dev'
            --exclude '.venv'
            --exclude 'db.sqlite3'
            --exclude 'node_modules'
            --exclude 'tmp'
            {{ project_name }} {{ project_dir }}

    - name: Clear out any files that shouldn't have been copied over
      ansible.builtin.file:
        path: "{{ item }}"
        state: absent
      with_items:
        - "{{ project_dir }}/{{ project_name }}/db.sqlite3"

    - name: Set some django settings for testing purposes
      ansible.builtin.lineinfile:
        search_string: "{{ item.search }}"
        line: "{{ item.replacement }}"
        path: "{{ project_dir }}/{{ project_name }}/.env"
      with_items:
        - search: "DEBUG="
          replacement: "DEBUG=True"
        - search: "ENVIRONMENT="
          replacement: "ENVIRONMENT=development"
        - search: "SEND_EMAILS="
          replacement: "SEND_EMAILS=False"
        - search: "LOG_LEVEL="
          replacement: "LOG_LEVEL=DEBUG"

    - name: Make sure the just commands have the pipenv environment variable set in Justfile
      ansible.builtin.lineinfile:
        line: 'export PIPENV_VENV_IN_PROJECT := "1"'
        path: "{{ project_dir }}/justfile"
        search_string: "export PIPENV_VENV_IN_PROJECT"
        validate: just --unstable --fmt --check --justfile %s

    - name: Install dependencies
      when: install_project_dependencies
      block:
        - name: Init a git repository for pre-commit
          ansible.builtin.command:
            cmd: git init
            chdir: "{{ project_dir }}"

        - name: Make an initial commit
          ansible.builtin.shell:
            cmd: git add . && git commit -m 'initial commit'
            chdir: "{{ project_dir }}"

        - name: Install project dependencies
          ansible.builtin.command:
            cmd: just install
            chdir: "{{ project_dir }}"

    - name: Setup project
      when: setup_project
      block:
        - name: Collect static files
          ansible.builtin.command:
            cmd: just collectstatic
            chdir: "{{ project_dir }}"

        - name: Create migrations
          ansible.builtin.command:
            cmd: just makemigrations
            chdir: "{{ project_dir }}"

        - name: Run migrations
          ansible.builtin.command:
            cmd: just migrate
            chdir: "{{ project_dir }}"

        - name: Create an insecure superuser
          ansible.builtin.command:
            cmd: just createsuperuser --noinput --username admin
            chdir: "{{ project_dir }}"
          environment:
            DJANGO_SUPERUSER_PASSWORD: admin

    - name: Open the directory
      block:
        - name: Check if open command exists
          ansible.builtin.command:
            cmd: which open
          register: open_command
          ignore_errors: yes

        - name: Open the directory
          ansible.builtin.command:
            cmd: open "{{ project_dir }}"
          when: open_command.rc == 0
