# Generated by Django 6.0.5 on 2026-05-15 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='pagetranslation',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='pagetranslation',
            constraint=models.UniqueConstraint(fields=('language_code', 'master'), name='pages_page_translation_uniq_lang'),
        ),
    ]
