# Generated by Django 6.0.5 on 2026-05-17 08:10

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenancy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('provider', models.CharField(choices=[('polar', 'Polar')], db_index=True, default='polar', max_length=50)),
                ('external_customer_id', models.CharField(db_index=True, max_length=255)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('name', models.CharField(blank=True, max_length=255)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='tenancy.team')),
            ],
            options={
                'verbose_name': 'Customer',
                'verbose_name_plural': 'Customers',
                'ordering': ['team__name', 'provider'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('provider', models.CharField(choices=[('polar', 'Polar')], db_index=True, default='polar', max_length=50)),
                ('external_product_id', models.CharField(db_index=True, max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('is_recurring', models.BooleanField(default=False)),
                ('recurring_interval', models.CharField(blank=True, max_length=50)),
                ('recurring_interval_count', models.PositiveIntegerField(blank=True, null=True)),
                ('is_archived', models.BooleanField(default=False)),
                ('prices', models.JSONField(blank=True, default=list)),
                ('benefits', models.JSONField(blank=True, default=list)),
                ('metadata', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
                'ordering': ['name'],
                'constraints': [models.UniqueConstraint(fields=('provider', 'external_product_id'), name='billing_unique_product_per_provider')],
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('provider', models.CharField(choices=[('polar', 'Polar')], db_index=True, default='polar', max_length=50)),
                ('external_subscription_id', models.CharField(db_index=True, max_length=255)),
                ('external_customer_id', models.CharField(blank=True, max_length=255)),
                ('external_product_id', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('incomplete', 'Incomplete'), ('incomplete_expired', 'Incomplete Expired'), ('trialing', 'Trialing'), ('active', 'Active'), ('past_due', 'Past Due'), ('canceled', 'Canceled'), ('unpaid', 'Unpaid'), ('revoked', 'Revoked')], default='incomplete', max_length=50)),
                ('amount', models.PositiveIntegerField(blank=True, null=True)),
                ('currency', models.CharField(blank=True, max_length=10)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('current_period_start', models.DateTimeField(blank=True, null=True)),
                ('current_period_end', models.DateTimeField(blank=True, null=True)),
                ('cancel_at_period_end', models.BooleanField(default=False)),
                ('canceled_at', models.DateTimeField(blank=True, null=True)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subscriptions', to='billing.customer')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subscriptions', to='billing.product')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='tenancy.team')),
            ],
            options={
                'verbose_name': 'Subscription',
                'verbose_name_plural': 'Subscriptions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Entitlement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('provider', models.CharField(choices=[('polar', 'Polar')], db_index=True, default='polar', max_length=50)),
                ('external_entitlement_id', models.CharField(blank=True, max_length=255)),
                ('key', models.CharField(max_length=255)),
                ('display_name', models.CharField(blank=True, max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('granted_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entitlements', to='billing.customer')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='tenancy.team')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entitlements', to='billing.product')),
                ('subscription', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entitlements', to='billing.subscription')),
            ],
            options={
                'verbose_name': 'Entitlement',
                'verbose_name_plural': 'Entitlements',
                'ordering': ['team__name', 'key'],
            },
        ),
        migrations.CreateModel(
            name='WebhookEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('provider', models.CharField(choices=[('polar', 'Polar')], db_index=True, default='polar', max_length=50)),
                ('external_event_id', models.CharField(db_index=True, max_length=255)),
                ('event_type', models.CharField(max_length=255)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('received', 'Received'), ('processed', 'Processed'), ('ignored', 'Ignored'), ('failed', 'Failed')], default='received', max_length=20)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Webhook Event',
                'verbose_name_plural': 'Webhook Events',
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('provider', 'external_event_id'), name='billing_unique_webhook_event_per_provider')],
            },
        ),
        migrations.AddConstraint(
            model_name='customer',
            constraint=models.UniqueConstraint(fields=('team', 'provider'), name='billing_unique_customer_per_team_provider'),
        ),
        migrations.AddConstraint(
            model_name='customer',
            constraint=models.UniqueConstraint(fields=('provider', 'external_customer_id'), name='billing_unique_customer_per_provider'),
        ),
        migrations.AddIndex(
            model_name='subscription',
            index=models.Index(fields=['team', 'provider', 'status'], name='billing_sub_team_id_567b07_idx'),
        ),
        migrations.AddConstraint(
            model_name='subscription',
            constraint=models.UniqueConstraint(fields=('provider', 'external_subscription_id'), name='billing_unique_subscription_per_provider'),
        ),
        migrations.AddIndex(
            model_name='entitlement',
            index=models.Index(fields=['team', 'key', 'is_active'], name='billing_ent_team_id_67939e_idx'),
        ),
        migrations.AddConstraint(
            model_name='entitlement',
            constraint=models.UniqueConstraint(fields=('team', 'provider', 'key'), name='billing_unique_entitlement_key_per_team_provider'),
        ),
    ]
