# Generated by Django 6.0.1 on 2026-01-07 12:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('billing', '0001_initial'),
        ('tenancy', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='tenancy.team'),
        ),
        migrations.AddIndex(
            model_name='subscription',
            index=models.Index(fields=['team', 'status'], name='billing_sub_team_id_b3a6b8_idx'),
        ),
    ]
