# Generated by Django 6.0.5 on 2026-05-15 14:53

import {{ project_name }}.users.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', {{ project_name }}.users.models.UserManager()),
            ],
        ),
    ]
