# Generated by Django 6.0.5 on 2026-05-15 16:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import {{ project_name }}.tokens.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenancy', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ApiToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('token_id', models.CharField(default={{ project_name }}.tokens.models.generate_token_id, editable=False, max_length=64, unique=True)),
                ('name', models.CharField(max_length=120)),
                ('lookup_id', models.CharField(db_index=True, max_length=16, unique=True)),
                ('secret_hash', models.CharField(max_length=128)),
                ('display_prefix', models.CharField(max_length=8)),
                ('environment', models.CharField(choices=[('live', 'Live'), ('test', 'Test')], default='live', max_length=10)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('scopes', models.JSONField(blank=True, default=list)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='tenancy.team')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_api_tokens', to=settings.AUTH_USER_MODEL)),
                ('revoked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='revoked_api_tokens', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'API Token',
                'verbose_name_plural': 'API Tokens',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='apitoken',
            index=models.Index(fields=['team', 'revoked_at'], name='tokens_apit_team_id_aada14_idx'),
        ),
    ]
