---
- name: Install dev dependencies
  hosts: localhost
  connection: local

  tasks:
    - name: Install dependencies (Ubuntu)
      apt:
        name: "{{ item }}"
        state: present
      with_items:
        - entr # File watcher
        - ripgrep # Fast search tool
      when: ansible_os_family == 'Debian'
      become: yes
