---
# This playbook is used to test the project template by executing the
# django-admin startproject command.
- hosts: localhost
  connection: local

  vars:
    clean_up: true
    project_name: temp_project

  tasks:
    - name: Generate a temporary directory for this test
      ansible.builtin.tempfile:
        state: directory
        prefix: ansible_django_project_template
      register: temp_dir

    - name: Create the temporary directory
      ansible.builtin.file:
        path: "{{ temp_dir.path }}"
        state: directory
      when: temp_dir.changed

    - name: Use the template to start a new Django project
      command:
        cmd: |
          pipenv run django-admin startproject 
            --template=django_project_template 
            --extension 'py,yaml,md,template,toml,json' 
            --name justfile 
            --exclude '.ruff_cache,db.sqlite3' 
            {{ project_name }} {{ temp_dir.path }}
        chdir: "{{ playbook_dir }}/../.."

    - name: Share the name of the temporary directory with the user
      debug:
        msg: "The new project is in {{ temp_dir.path }}/{{ project_name }}"

    - name: Open the directory (on macOS)
      command:
        cmd: open "{{ temp_dir.path }}"
      when: ansible_os_family == 'Darwin'
